### PR TITLE
custom db schema support

### PR DESCRIPTION
**Pull request by Kulak**
I added custom schema support.  It seems that tests are the most impacted by the change.

### CODE REVIEW

**Comment by Kulak** [comment]
lint failed and failed status did not get updated after the change

**Comment by Kulak** [comment]
I am not sure why lint is marked as failed.  Here is output I've got:

```
==> Linting with golangci-lint
level=info msg="[config_reader] Config search paths: [./ /app /]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active 3 linters: [gofmt goimports golint]"
level=info msg="[loader] Go packages loading at mode 575 (files|imports|name|types_sizes|compiled_files|deps|exports_file) took 5.48880259s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 2.393519ms"
level=info msg="[linters context/goanalysis] analyzers took 37.977896ms with top 10 stages: goimports: 20.070613ms, gofmt: 11.072736ms, golint: 6.834547ms"
level=info msg="[runner] processing took 2.09µs with stages: max_same_issues: 441ns, skip_dirs: 264ns, max_from_linter: 175ns, autogenerated_exclude: 169ns, nolint: 161ns, cgo: 118ns, path_prettifier: 109ns, filename_unadjuster: 107ns, skip_files: 104ns, identifier_marker: 102ns, diff: 89ns, exclude-rules: 47ns, uniq_by_line: 42ns, max_per_file_from_linter: 42ns, exclude: 41ns, source_code: 40ns, path_shortener: 39ns"
level=info msg="[runner] linters took 161.089167ms with stages: goanalysis_metalinter: 161.058155ms"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 58 samples, avg is 72.1MB, max is 136.3MB"
level=info msg="Execution took 5.663067638s"
```

**Comment by vgarvardt** [comment]
Hi, @Kulak. I just merged golangci action fix https://github.com/vgarvardt/gue/pull/29 - please rebase your branch and it should work.

**Comment by vgarvardt** [comment]
Tbh I do not think schema should be managed on the library level since it can be easily set on the connection level. Application manages a connection pool - the library only uses existing pool. E.g. for `pq` driver schema can be set with `search_path`, e.g. `search_path=myschema,public`, so if the `gue_jobs` table is created in `myschema` while the rest of the application tables are installed to `public` queries should work w.out any modification.

Let me try to add a test for this to double check if it really works like this.

**Comment by vgarvardt** [comment]
I wrote a test in https://github.com/vgarvardt/gue/pull/30 to demonstrate my idea - gue migration is explicitly applied to `gue` schema and some another table explicitly installed to `foo` schema. After all the migrations are applied queries on both tables w/out setting schema explicitly work fine with `search_path=foo,gue` set to connection string parameters.

I borrowed migrations sync-related code for different schemas from your PR.

**Comment by Kulak** [comment]
I did not know that I can connect to specific schema at connection level.  I don't mind using that method.  Thank you

**Pull request closed without merging**
