### PR TITLE
add worker index to context

### LINKED ISSUE #88: Add context to worker
I am researching que systems and this looks really promising but I was wondering how can i add context to a given worker, at minimum i need to get ids numeric id, but beeing able to provide it with aditional context would be nice aswell.

### PR DESCRIPTION
**Pull request by bjartek**
In order to know what worker calls each job, if that is needed, i added workerIndex to the context the job is called with fixes #88

### CODE REVIEW

**Comment by vgarvardt** [comment]
What problem are you trying to solve with this?

Currently you can find a worker ID in the `worker-id` log context field, for the pool it has the following format `%s/worker-%d`, where the first string placeholder is the pool id, either randomly generated or explicitly set using pool options, and the second numeric placeholder is the worker index in the pool. So in should look like something like this in the log `sAd6yh/worker-0`, `sAd6yh/worker-1`, etc.

**Comment by bjartek** [comment]
I need to know in code each workers identity because the jobs i am going to run are using a resource that has to be locked to each worker. (A key to sign a blockchain transaction)

**Comment by vgarvardt** [comment]
https://github.com/vgarvardt/gue/pull/91 should solve your problem, will create new beta release so you could test it.

**Comment by bjartek** [comment]
Awesome!

**Pull request closed without merging**
